const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Plugins.TextBox,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Spritefont2,
		C3.Behaviors.wrap,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.shadowlight,
		C3.Plugins.Particles,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.urlencode,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.Arr.Acts.Reverse,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{PlayButton: 0},
	{CloseButton: 0},
	{SoundButton: 0},
	{Name: 0},
	{Pause: 0},
	{Ui: 0},
	{TypeName: 0},
	{gamefullscreen: 0},
	{optionButton: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{MobileAdvert: 0},
	{TextInput: 0},
	{HighsCores: 0},
	{JSON: 0},
	{AJAX: 0},
	{Array: 0},
	{SpriteFontEggs: 0},
	{ID: 0},
	{SpriteFontUi: 0},
	{SpriteFont: 0},
	{FullScreen: 0},
	{pausebutton: 0},
	{diamond: 0},
	{fishbone: 0},
	{restart2: 0},
	{home: 0},
	{Speed: 0},
	{Wrap: 0},
	{Clouds: 0},
	{Black: 0},
	{EndLine: 0},
	{Help: 0},
	{MENU: 0},
	{Restart: 0},
	{Scores: 0},
	{Share: 0},
	{ShareChoose: 0},
	{Skip: 0},
	{Sky: 0},
	{SOUND: 0},
	{Rotate: 0},
	{Star3: 0},
	{Start: 0},
	{Active: 0},
	{Tap: 0},
	{Play: 0},
	{WhiteBox: 0},
	{Wish: 0},
	{TotalItemsCollected: 0},
	{TotalItemsMissed: 0},
	{Pin: 0},
	{diver: 0},
	{Keyboard: 0},
	{english: 0},
	{maltese: 0},
	{GoButton: 0},
	{TotalItemsCollectedFinal: 0},
	{TotalItemsMissedFinal: 0},
	{English: 0},
	{Maltese: 0},
	{EnglishText: 0},
	{MalteseText: 0},
	{Fall: 0},
	{Eggs: 0},
	{Bomb: 0},
	{Bucket: 0},
	{Bucket2: 0},
	{Underwater: 0},
	{logo_menu: 0},
	{PlayText: 0},
	{underwaterbackground: 0},
	{lefttopmenu: 0},
	{fullscreen2: 0},
	{mute: 0},
	{fishbone2: 0},
	{Button: 0},
	{Fullscreengame: 0},
	{game_fullscreen: 0},
	{ShadowLight: 0},
	{EnterNicknameText: 0},
	{startx: 0},
	{starty: 0},
	{airbubbles: 0},
	{LeaderBoard: 0},
	{leaderboard2: 0},
	{trivia4x: 0},
	{Triviachallenge: 0},
	{QuestionText: 0},
	{rightAnswerID: 0},
	{optionButtonNumber: 0},
	{rightAnswer: 0},
	{QuestionOption1: 0},
	{QuestionOption2: 0},
	{QuestionOption3: 0},
	{SOBlogo2x: 0},
	{netbar: 0},
	{next: 0},
	{nexticon: 0},
	{anchor: 0},
	{Text4: 0},
	{Quiz: 0},
	{TriviaChallenge2: 0},
	{pausemenu: 0},
	{buttonNumber: 0},
	{pausebutton2: 0},
	{pausetomenubutton: 0},
	{Font: 0},
	{swimming: 0},
	{lefttoright: 0},
	{fish: 0},
	{OptionButtonNumber: 0},
	{RightAnswer: 0},
	{isRightAnswer: 0},
	{quizOptionButton: 0},
	{maggie: 0},
	{Particles: 0},
	{gameover: 0},
	{isGameOver: 0},
	{MoveTo: 0},
	{speechbubble: 0},
	{WellDoneText: 0},
	{Button2: 0},
	{QuizOkButton: 0},
	{QuizOkText: 0},
	{seashellbullet: 0},
	{QuizBonusPoints: 0},
	{TotalScore: 0},
	{Text: 0},
	{sadmaggie: 0},
	{facebook: 0},
	{twitter: 0},
	{ShareText: 0},
	{MEEELogo: 0},
	{FinalScoreText: 0},
	{QuizResultBG: 0},
	{winEnglish: 0},
	{winMaltese: 0},
	{loseEnglish: 0},
	{loseMaltese: 0},
	{QuizResultText: 0},
	{Tween: 0},
	{Fade: 0},
	{PointText: 0},
	{Sprite: 0},
	{MusicButton: 0},
	{GameName: 0},
	{url: 0},
	{OpenURL: 0},
	{GameIcon: 0},
	{OurOtherGames: 0},
	{LanguageButton: 0},
	{LanguageText: 0},
	{option: 0},
	{AnswerSymbol: 0},
	{Mouse: 0},
	{FullScreenWarningBG: 0},
	{FullScreenWarning: 0},
	{Type: 0},
	{FullScreenWarningButton: 0},
	{OkText: 0},
	{Fireflies: 0},
	{Sparkles: 0},
	{Spark: 0},
	{TriviaOkButton: 0},
	{Background: 0},
	{Timer: 0},
	{Buttons: 0},
	{triviaOptions: 0},
	{currentLevel: 0},
	{selectDidYouKnow: 0},
	{isIphone: 0},
	{currentLayout: 0},
	{web_app_url: 0},
	{highscores: 0},
	{s: 0},
	{updatedScore: 0},
	{name: 0},
	{score: 0},
	{ChoseEnglish: 0},
	{isPc: 0},
	{questionGenerated: 0},
	{answered: 0},
	{PauseNo: 0},
	{Miss: 0},
	{MaxBomb: 0},
	{MaxCollectedItems: 0},
	{MaxMiss: 0},
	{CollectedItems: 0},
	{quizBonusPoints: 0},
	{quizQuestionID: 0},
	{RightAnswerFromJSON: 0},
	{LastLevel: 0},
	{PerScore: 0},
	{GlobalFontSize: 0},
	{triviaQuestionID: 0},
	{RightAnswerFromTheJSON: 0},
	{triviaAnswerSelected: 0},
	{GameScore: 0},
	{targetCompleted: 0},
	{diverNextFrame: 0},
	{targetXPos: 0},
	{TriviaShown: 0},
	{RandomParticleSpawn: 0},
	{targetYPos: 0},
	{BannerID: 0},
	{InterstitialID: 0}
];

self.InstanceType = {
	PlayButton: class extends self.ISpriteInstance {},
	CloseButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	Name: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Ui: class extends self.ISpriteInstance {},
	TypeName: class extends self.ISpriteInstance {},
	gamefullscreen: class extends self.ISpriteInstance {},
	optionButton: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	TextInput: class extends self.ITextInputInstance {},
	HighsCores: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	SpriteFontEggs: class extends self.ISpriteFontInstance {},
	SpriteFontUi: class extends self.ISpriteFontInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	FullScreen: class extends self.ISpriteInstance {},
	pausebutton: class extends self.ISpriteInstance {},
	diamond: class extends self.ISpriteInstance {},
	fishbone: class extends self.ISpriteInstance {},
	restart2: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	EndLine: class extends self.ISpriteInstance {},
	Help: class extends self.ISpriteInstance {},
	MENU: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	Scores: class extends self.ISpriteInstance {},
	Share: class extends self.ISpriteInstance {},
	ShareChoose: class extends self.ISpriteInstance {},
	Skip: class extends self.ISpriteInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	SOUND: class extends self.ISpriteInstance {},
	Star3: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	Tap: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	WhiteBox: class extends self.ISpriteInstance {},
	Wish: class extends self.ISpriteInstance {},
	TotalItemsCollected: class extends self.ITextInstance {},
	TotalItemsMissed: class extends self.ITextInstance {},
	diver: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	GoButton: class extends self.ITextInstance {},
	TotalItemsCollectedFinal: class extends self.ITextInstance {},
	TotalItemsMissedFinal: class extends self.ITextInstance {},
	English: class extends self.ISpriteInstance {},
	Maltese: class extends self.ISpriteInstance {},
	EnglishText: class extends self.ITextInstance {},
	MalteseText: class extends self.ITextInstance {},
	Eggs: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Bucket: class extends self.ISpriteInstance {},
	Bucket2: class extends self.ISpriteInstance {},
	Underwater: class extends self.ISpriteInstance {},
	logo_menu: class extends self.ISpriteInstance {},
	PlayText: class extends self.ITextInstance {},
	underwaterbackground: class extends self.ISpriteInstance {},
	lefttopmenu: class extends self.ISpriteInstance {},
	fullscreen2: class extends self.ISpriteInstance {},
	mute: class extends self.ISpriteInstance {},
	fishbone2: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Fullscreengame: class extends self.IButtonInstance {},
	game_fullscreen: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	EnterNicknameText: class extends self.ITextInstance {},
	airbubbles: class extends self.ISpriteInstance {},
	LeaderBoard: class extends self.ITextInstance {},
	leaderboard2: class extends self.ISpriteInstance {},
	trivia4x: class extends self.ISpriteInstance {},
	Triviachallenge: class extends self.ISpriteInstance {},
	QuestionText: class extends self.ITextInstance {},
	QuestionOption1: class extends self.ITextInstance {},
	QuestionOption2: class extends self.ITextInstance {},
	QuestionOption3: class extends self.ITextInstance {},
	SOBlogo2x: class extends self.ISpriteInstance {},
	netbar: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	nexticon: class extends self.ISpriteInstance {},
	anchor: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Quiz: class extends self.ISpriteInstance {},
	TriviaChallenge2: class extends self.ISpriteInstance {},
	pausemenu: class extends self.ISpriteInstance {},
	pausebutton2: class extends self.ISpriteInstance {},
	pausetomenubutton: class extends self.ISpriteInstance {},
	Font: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	quizOptionButton: class extends self.ISpriteInstance {},
	maggie: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	speechbubble: class extends self.ISpriteInstance {},
	WellDoneText: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	QuizOkButton: class extends self.ISpriteInstance {},
	QuizOkText: class extends self.ITextInstance {},
	seashellbullet: class extends self.ISpriteInstance {},
	QuizBonusPoints: class extends self.ITextInstance {},
	TotalScore: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	sadmaggie: class extends self.ISpriteInstance {},
	facebook: class extends self.ISpriteInstance {},
	twitter: class extends self.ISpriteInstance {},
	ShareText: class extends self.ITextInstance {},
	MEEELogo: class extends self.ISpriteInstance {},
	FinalScoreText: class extends self.ITextInstance {},
	QuizResultBG: class extends self.ISpriteInstance {},
	QuizResultText: class extends self.ITextInstance {},
	PointText: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MusicButton: class extends self.ISpriteInstance {},
	GameName: class extends self.ITextInstance {},
	OpenURL: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	OurOtherGames: class extends self.ISpriteInstance {},
	LanguageButton: class extends self.ISpriteInstance {},
	LanguageText: class extends self.ITextInstance {},
	AnswerSymbol: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	FullScreenWarningBG: class extends self.ISpriteInstance {},
	FullScreenWarning: class extends self.ITextInstance {},
	FullScreenWarningButton: class extends self.ISpriteInstance {},
	OkText: class extends self.ITextInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	Sparkles: class extends self.IParticlesInstance {},
	Spark: class extends self.ISpriteInstance {},
	TriviaOkButton: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Timer: class extends self.ITextInstance {},
	Buttons: class extends self.ISpriteInstance {},
	triviaOptions: class extends self.ITextInstance {}
}